import User from "../models/User.js";
import validator from "validator";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import { use } from "react";

const JWT_SECRET = "your_jwt_secret_key";
const TOCKEN_EXPIRY = "24h";

const createToken = (userId) => {
    jwt.sign({ id:userId }, JWT_SECRET, { expiresIn: TOCKEN_EXPIRY });
}


//to register a new user
export async function registerUser(req, res) {
    const { name, email, password } = req.body; 
    if(!name || !email || !password) {
        return res.status(400).json({
            success: false,
            message: "Please provide name, email and password"
        })
    }
    if(!validator.isEmail(email)) {
        return res.status(400).json({
            success: false,
            message: "Please provide a valid email"
        })
    }

    if(password.length < 8) {
        return res.status(400).json({
            success: false,
            message: "Password must be at least 8 characters long"
        })
    }

    try{
        if(await User.findOne({email})) {
            return res.status(400).json({
                success: false,
                message: "User already exists"
            })
        }

        const hashed = await bcrypt.hash(password, 10);  //by adding salt to the password we can make it more secure and harder to crack
        const user = await User.create({name,email,password: hashed});  

        const token = createToken(user._id);

        res.status(201).json({
            success: true,
            token,
            user: {
                id: user._id,name: user.name,email: user.email
            }            
        });
    }
    catch(error) {
        console.error(error);
        res.status(500).json({
            success: false,
            message: "Server error"
        });
    }
}



//to login as user
export async function loginUser(req, res) {
    const { email, password } = req.body;   
    if(!email || !password) {
        return res.status(400).json({
            success: false,
            message: "Please provide email and password"
        });
    }
//"400 indicates a bad request due to invalid input from the client, whereas 401 indicates that the user is not authenticated and needs to log in." 
    try {
        const user = await User.findOne({ email });
        if(!user) {
            return res.status(401).json({
                success: false,
                message: "Invalid credentials"
            });
        }
        const match = await bcrypt.compare(password, user.password);
        if(!match) {
            return res.status(401).json({
                success: false,
                message: "Invalid credentials"
            });
        }

        const token = createToken(user._id);       
        //._id is the unique identifier for the user in the database, which is generated by MongoDB when a new user document is created. This ID is used to identify the user and associate it with the generated JWT token. 
        
        res.json({
            success: true,
            token,
            user: {
                id: user._id,name: user.name,email: user.email
            }
        });
 
    }
    catch(err) {
        console.error(err);
        res.status(500).json({
            success: false,
            message: "Server error"
        });
    }
}


//to get user details

export async function getCurrentUser(req, res) {
    try{
        const user = await User.findById(req.user.id).select("name email");
        if(!user) {
            return res.status(404).json({
                success: false,
                message: "User not found"
            });
        }
        res.json({
            success: true,
            user
        });
    }
    catch(err) {
        console.error(err);
        res.status(500).json({
            success: false,
            message: "Server error"
        });
    }
}

