version: "3.9"

services:

  backend:
    build: ./backend
    ports:
      - "5000:4000"
    env_file:
      - ./.env.local
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  mongodb:
    image: mongo:8
    container_name: mongodb
    restart: always

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: